-- UTOM V2 M1.4 additive schema foundation: v2_ai_runs
CREATE TABLE v2_ai_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  article_id BIGINT UNSIGNED NULL,
  step_name VARCHAR(64) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  model VARCHAR(128) NOT NULL,
  prompt_version VARCHAR(64) NOT NULL,
  extractor_version VARCHAR(64) NOT NULL,
  schema_version VARCHAR(64) NOT NULL,
  input_hash CHAR(64) NOT NULL,
  sanitized_input_ref VARCHAR(512) NULL,
  status VARCHAR(24) NOT NULL,
  retry_count INT UNSIGNED NOT NULL DEFAULT '0',
  started_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6) NULL,
  input_tokens INT UNSIGNED NULL,
  output_tokens INT UNSIGNED NULL,
  estimated_cost DECIMAL(12,6) NULL,
  cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
  escalation_reason VARCHAR(255) NULL,
  structured_result_ref VARCHAR(512) NULL,
  error_metadata JSON NULL,
  operation_key CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_v2_ai_runs_operation_key (operation_key),
  KEY idx_v2_ai_runs_article_id_step_name (article_id, step_name),
  KEY idx_v2_ai_runs_status_started_at (status, started_at),
  KEY idx_v2_ai_runs_provider_model (provider, model),
  CONSTRAINT fk_v2_ai_runs_article_id_1 FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
