-- UTOM V2 M1.4 additive schema foundation: v2_claims
CREATE TABLE v2_claims (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  subject_entity_id BIGINT UNSIGNED NULL,
  predicate VARCHAR(128) NOT NULL,
  object_entity_id BIGINT UNSIGNED NULL,
  value_json JSON NULL,
  normalized_value VARCHAR(512) NULL,
  claim_type VARCHAR(64) NOT NULL,
  article_id BIGINT UNSIGNED NOT NULL,
  source_id BIGINT UNSIGNED NULL,
  valid_from DATETIME(6) NULL,
  valid_until DATETIME(6) NULL,
  observed_at DATETIME(6) NOT NULL,
  publication_time DATETIME(6) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'observed',
  confidence DECIMAL(5,4) NULL,
  extraction_run_id BIGINT UNSIGNED NULL,
  claim_group_id BIGINT UNSIGNED NULL,
  superseded_by BIGINT UNSIGNED NULL,
  observation_key CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_v2_claims_observation_key (observation_key),
  KEY idx_v2_claims_subject_entity_id_predicate (subject_entity_id, predicate),
  KEY idx_v2_claims_article_id (article_id),
  KEY idx_v2_claims_source_id (source_id),
  KEY idx_v2_claims_status (status),
  KEY idx_v2_claims_claim_group_id (claim_group_id),
  CONSTRAINT fk_v2_claims_subject_entity_id_1 FOREIGN KEY (subject_entity_id) REFERENCES v2_entities (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_object_entity_id_2 FOREIGN KEY (object_entity_id) REFERENCES v2_entities (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_article_id_3 FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_source_id_4 FOREIGN KEY (source_id) REFERENCES sources (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_extraction_run_id_5 FOREIGN KEY (extraction_run_id) REFERENCES v2_ai_runs (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_claim_group_id_6 FOREIGN KEY (claim_group_id) REFERENCES v2_claim_groups (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_v2_claims_superseded_by_7 FOREIGN KEY (superseded_by) REFERENCES v2_claims (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
