"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { STEP_NAME, validateBackfillInput, runIncrementalBackfill } = require("../../lib/v2/incremental-backfill");
const budget = { limits: { dailyCost: 10, monthlyCost: 100, perArticleCost: 5, perStepCost: 2 }, usage: { dailyCost: 0, monthlyCost: 0, perArticleCost: 0, perStepCost: 0 } };
function fakeRepository(articles, completed = new Map(), options = {}) {
  const calls = []; let rolledBack = false;
  return { calls, get rolledBack() { return rolledBack; }, async withTransaction(work) { calls.push("begin"); try { const result = await work({
    async listArticlesAfter(cursor, limit) { calls.push(["list", cursor, limit]); return articles.filter((a) => a.id > cursor).slice(0, limit); },
    async claimStep({ articleId, claimToken }) { calls.push(["claim", articleId]); if (completed.has(articleId)) return { status: "completed", outputRef: completed.get(articleId) }; if (options.busyId === articleId) return { status: "busy" }; return { status: "claimed", claimToken }; },
    async persistDecision({ articleId }) { calls.push(["decision", articleId]); },
    async completeStep({ articleId, claimToken, outputRef }) { calls.push(["complete", articleId, claimToken, outputRef]); completed.set(articleId, outputRef); if (options.failId === articleId) throw new Error("db_failure"); },
  }); calls.push("commit"); return result; } catch (error) { rolledBack = true; calls.push("rollback"); throw error; } } };
}
test("M17 validates bounded cursor and batch input", () => { assert.equal(validateBackfillInput({ batchSize: 0 }).status, "invalid"); assert.equal(validateBackfillInput({ batchSize: 2, cursor: 4, maxItems: 2 }).status, "valid"); });
test("M17 pauses and resumes with deterministic checksum", async () => { const repo = fakeRepository([{ id: 1, contentHash: "a", updatedAt: "2026-01-01" }, { id: 2, contentHash: "b", updatedAt: "2026-01-01" }, { id: 3, contentHash: "c", updatedAt: "2026-01-01" }]); const first = await runIncrementalBackfill({ repository: repo, input: { batchSize: 2 }, budget, processArticle: async (a) => ({ outputRef: `r-${a.id}`, cost: 0 }) }); assert.equal(first.status, "paused"); assert.equal(first.nextCursor, 2); const second = await runIncrementalBackfill({ repository: repo, input: { batchSize: 2, cursor: first.nextCursor }, budget, processArticle: async (a) => ({ outputRef: `r-${a.id}`, cost: 0 }) }); assert.equal(second.status, "completed"); assert.equal(second.nextCursor, 3); assert.equal(first.checksum.length, 64); });
test("M17 duplicate run reuses completed step without processing twice", async () => { const done = new Map([[1, "existing"]]); const repo = fakeRepository([{ id: 1, contentHash: "a", updatedAt: "2026-01-01" }], done); const result = await runIncrementalBackfill({ repository: repo, input: { batchSize: 1 }, budget, processArticle: async () => { throw new Error("must_not_run"); } }); assert.equal(result.reused, 1); assert.equal(result.processed, 1); assert.equal(repo.calls.filter((c) => Array.isArray(c) && c[0] === "complete").length, 0); });
test("M17 busy claim does not advance cursor past unfinished item", async () => { const repo = fakeRepository([{ id: 5, contentHash: "a", updatedAt: "2026-01-01" }], new Map(), { busyId: 5 }); const result = await runIncrementalBackfill({ repository: repo, input: { batchSize: 1, cursor: 0 }, budget }); assert.equal(result.status, "paused"); assert.equal(result.nextCursor, 0); assert.equal(result.skipped, 1); });
test("M17 DB failure rolls back and cost ceiling prevents completion", async () => { const repo = fakeRepository([{ id: 1, contentHash: "a", updatedAt: "2026-01-01" }], new Map(), { failId: 1 }); await assert.rejects(() => runIncrementalBackfill({ repository: repo, input: { batchSize: 1, costCeiling: 0 }, budget, processArticle: async () => ({ cost: 1 }) }), /cost_ceiling_exceeded/); assert.equal(repo.rolledBack, true); });
test("M17 feature off is inert", async () => { const repo = fakeRepository([{ id: 1 }]); const result = await runIncrementalBackfill({ repository: repo, input: { featureEnabled: false }, budget }); assert.equal(result.status, "disabled"); assert.deepEqual(repo.calls, []); });
console.log(`M17 incremental backfill regression: ${STEP_NAME} PASS`);
const { createIncrementalBackfillRepository } = require("../../lib/v2/incremental-backfill-repository");
test("M17 pool adapter owns one transaction connection and releases it", async () => {
  const calls = []; const connection = { async beginTransaction() { calls.push("begin"); }, async commit() { calls.push("commit"); }, async rollback() { calls.push("rollback"); }, release() { calls.push("release"); }, async execute(sql) { calls.push(sql); if (sql.startsWith("SELECT")) return [[{ id: 1, contentHash: "a", contentText: "body", updatedAt: "2026-01-01" }]]; return [{ affectedRows: 1 }]; } }; const pool = { async getConnection() { calls.push("getConnection"); return connection; }, async execute() { throw new Error("pool must not execute directly"); } }; const repo = createIncrementalBackfillRepository(pool); await repo.withTransaction(async (tx) => { await tx.listArticlesAfter(0, 1); }); assert.deepEqual(calls.slice(0, 3), ["getConnection", "begin", "SELECT id,content_hash contentHash,content_text contentText,updated_at updatedAt FROM articles WHERE id>? ORDER BY id ASC LIMIT ?"]); assert.deepEqual(calls.slice(-2), ["commit", "release"]);
});
